---
  - 'archive'
  - 'bank'
  - 'beer'
  - 'bell'
  - 'bolt'
  - 'bomb'
  - 'book'
  - 'bookmark'
  - 'briefcase'
  - 'building'
  - 'bullhorn'
  - 'bus'
  - 'calculator'
  - 'calendar'
  - 'chain'
  - 'check'
  - 'coffee'
  - 'credit-card'
  - 'diamond'
  - 'dollar'
  - 'envelope'
  - 'euro'
  - 'flag'
  - 'heart'
  - 'home'
