---
  home:      '&#xf015;'
  archive:   '&#xf187;'
  bank:      '&#xf19c;'
  beer:      '&#xf0fc;'
  bell:      '&#xf0f3;'
  bolt:      '&#xf0e7;'
  bomb:      '&#xf1e2;'
  book:      '&#xf02d;'
  bookmark:  '&#xf02e;'
  briefcase: '&#xf0b1;'
  building:  '&#xf1ad;'
