---
  archive:     '&#xf187;'
  bank:        '&#xf19c;'
  beer:        '&#xf0fc;'
  bell:        '&#xf0f3;'
  bolt:        '&#xf0e7;'
  bomb:        '&#xf1e2;'
  book:        '&#xf02d;'
  bookmark:    '&#xf02e;'
  briefcase:   '&#xf0b1;'
  building:    '&#xf1ad;'
  bullhorn:    '&#xf0a1;'
  bus:         '&#xf207;'
  calculator:  '&#xf1ec;'
  calendar:    '&#xf073;'
  chain:       '&#xf0c1;'
  check:       '&#xf00c;'
  coffee:      '&#xf0f4;'
  credit-card: '&#xf09d;'
  diamond:     '&#xf219;'
  dollar:      '&#xf155;'
  envelope:    '&#xf0e0;'
  euro:        '&#xf153;'
  flag:        '&#xf024;'
  heart:       '&#xf004;'
  home:        '&#xf015;'
